name: Continuous Integration - Synapse Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Pytest
        run: pip install pytest

      - name: Executar Testes Automatizados
        run: pytest test_middleware.py
