name: Continuous Integration - Synapse Suite

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/configure-pages@v3 # Usando action nativa padrão
        with:
          python-version: '3.10'

      - name: Instalar Pytest
        run: pip install pytest

      - name: Executar Testes Automatizados
        run: pytest test_middleware.py
        
